"""Add item name in operation

Revision ID: 8dcbe0e050d0
Revises: d42ecb918e1b
Create Date: 2023-09-15 20:29:12.971418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8dcbe0e050d0'
down_revision: Union[str, None] = 'd42ecb918e1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operation', sa.Column('item_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('operation', 'item_name')
    # ### end Alembic commands ###